all:
  children:
    web_servers:
      hosts:
        web1:
          ansible_host: 192.168.0.17
          ansible_user: root
        web2:
          ansible_host: 192.168.0.18
          ansible_user: root
    
    db_servers:
      hosts:
        db1:
          ansible_host: 192.168.0.19
          ansible_user: root
          db_role: primary
        db2:
          ansible_host: 192.168.0.20
          ansible_user: root
          db_role: replica
    
    monitoring:
      hosts:
        monitor1:
          ansible_host: 192.168.0.21
          ansible_user: root

  vars:
    ansible_python_interpreter: /usr/bin/python3
    timezone: Asia/Krasnoyarsk
